# Generated by Django 4.1.3 on 2022-11-06 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=100)),
                ('likes', models.IntegerField(default='0')),
                ('dislikes', models.IntegerField(default='0')),
                ('date', models.CharField(default=' ', max_length=100)),
                ('thumbnail', models.ImageField(default=None, upload_to='thumbnail_uploaded')),
                ('video', models.FileField(default=None, upload_to='videos-uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
    ]
