# Generated by Django 4.1.3 on 2022-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0005_newvideo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newvideo',
            name='id',
        ),
        migrations.AddField(
            model_name='newvideo',
            name='videoID',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
