# Generated by Django 4.1.3 on 2022-11-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0006_remove_newvideo_id_newvideo_videoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newvideo',
            name='videoID',
        ),
        migrations.AddField(
            model_name='newvideo',
            name='id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='newvideo',
            name='visits',
            field=models.IntegerField(default='0'),
        ),
    ]
