# Generated by Django 4.1.3 on 2022-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0008_alter_comment_user_alter_newvideo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
